In [2]:
import pandas as pd

### Exercício 1 - 4

In [10]:
df = pd.read_csv('datasets/distribuicao_respiradores_BR.csv',sep=';')

In [11]:
df.head(10)

,DATA,FORNECEDOR,DESTINO,ESTADO/MUNICIPIO,TIPO,QUANTIDADE,VALOR,DESTINATARIO,UF
0,19/04/2020,VYAIRE,RIO DE JANEIRO,ESTADO,UTI,40,2400000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
1,22/04/2020,VYAIRE,RIO DE JANEIRO,ESTADO,UTI,20,1200000,LABORATÓRIO QUÍMICO FARMACÊUTICO DE AERONÁUTICA,RJ
2,08/05/2020,MAGNAMED,RIO DE JANEIRO,ESTADO,UTI,25,1500000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
3,08/05/2020,KTK,RIO DE JANEIRO,ESTADO,UTI,15,900000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
4,09/05/2020,LEISTUNG,RIO DE JANEIRO,ESTADO,UTI,6,360000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
5,09/05/2020,VYAIRE,RIO DE JANEIRO,ESTADO,UTI,1,60000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
6,09/05/2020,VYAIRE,RIO DE JANEIRO,ESTADO,UTI,30,1800000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
7,09/05/2020,MAGNAMED,RIO DE JANEIRO,ESTADO,UTI,8,480000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
8,09/05/2020,MAGNAMED,RIO DE JANEIRO,ESTADO,TRANSPORTE,4,193160,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ
9,09/05/2020,MAGNAMED,RIO DE JANEIRO,ESTADO,UTI,1,60000,ALMOXARIFADO ESTADUAL DE MEDICAMENTOS - RIO DE...,RJ

In [12]:
df.tail(3)

,DATA,FORNECEDOR,DESTINO,ESTADO/MUNICIPIO,TIPO,QUANTIDADE,VALOR,DESTINATARIO,UF
1602,24/09/2020,KTK,PARANA,MUNICIPIO,UTI,2,120000,SMS de GUAIRA,PR
1603,24/09/2020,VYAIRE LTV 2200 USA,PARANA,MUNICIPIO,TRANSPORTE USA,1,63125,SMS de GUAIRA,PR
1604,07/08/2020,MAGNAMED,LIBANO,-,TRANSPORTE,300,14487000,MISSÃO FAB (Doação Destino ao Libano).,-

In [15]:
colunas = df.columns

In [18]:
print(colunas)

Index(['DATA', 'FORNECEDOR', 'DESTINO', 'ESTADO/MUNICIPIO', 'TIPO',
       'QUANTIDADE', 'VALOR', 'DESTINATARIO', 'UF'],
      dtype='str')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1605 entries, 0 to 1604
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATA              1605 non-null   str
 1   FORNECEDOR        1605 non-null   str
 2   DESTINO           1605 non-null   str
 3   ESTADO/MUNICIPIO  1605 non-null   str
 4   TIPO              1605 non-null   str
 5   QUANTIDADE        1605 non-null   int64
 6   VALOR             1605 non-null   int64
 7   DESTINATARIO      1605 non-null   str
 8   UF                1605 non-null   str
dtypes: int64(2), str(7)
memory usage: 113.0 KB

In [22]:
df.dtypes

DATA                  str
FORNECEDOR            str
DESTINO               str
ESTADO/MUNICIPIO      str
TIPO                  str
QUANTIDADE          int64
VALOR               int64
DESTINATARIO          str
UF                    str
dtype: object

In [20]:
df.shape[0]

1605

In [23]:
df.isna().sum()

DATA                0
FORNECEDOR          0
DESTINO             0
ESTADO/MUNICIPIO    0
TIPO                0
QUANTIDADE          0
VALOR               0
DESTINATARIO        0
UF                  0
dtype: int64

In [27]:
df['DATA'].head(3)

0    19/04/2020
1    22/04/2020
2    08/05/2020
Name: DATA, dtype: str

In [30]:
df['DATA'] = pd.to_datetime(df['DATA'], errors='coerce')

C:\Users\bob\AppData\Local\Temp\ipykernel_17820\2901336791.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['DATA'] = pd.to_datetime(df['DATA'], errors='coerce')

In [31]:
df['DATA'].head(3)

0   2020-04-19
1   2020-04-22
2   2020-05-08
Name: DATA, dtype: datetime64[us]

In [33]:
df['VALOR'].head(3)

0    2400000
1    1200000
2    1500000
Name: VALOR, dtype: int64

In [34]:
df['VALOR'] = df['VALOR'].astype(float)

In [35]:
df['VALOR'].head(3)

0    2400000.0
1    1200000.0
2    1500000.0
Name: VALOR, dtype: float64

In [36]:
df['FORNECEDOR'].unique()

<StringArray>
[                              'VYAIRE',
                             'MAGNAMED',
                                  'KTK',
                             'LEISTUNG',
                      'LEISTUNG/VYAIRE',
                           'KTK/VAYIRE',
                                  'WEG',
                  'VYAIRE LTV 2200 USA',
                                  'UTI',
                  'VYAIRE LTV 1200 USA',
                  'MAGNAMED-REQUISIÇÃO',
              'SUZANO/Zhongxun Medical',
                        'SUZANO/Resmed',
 'L C DADDE COM AT INST MAT MEDICO EPP',
                  'MAGNAMED/REQUISIÇÃO',
                             'Leistung']
Length: 16, dtype: str

In [41]:
df['FORNECEDOR'].unique()

<StringArray>
[                              'VYAIRE',
                             'MAGNAMED',
                                  'KTK',
                             'LEISTUNG',
                      'LEISTUNG/VYAIRE',
                           'KTK/VAYIRE',
                                  'WEG',
                  'VYAIRE LTV 2200 USA',
                                  'UTI',
                  'VYAIRE LTV 1200 USA',
                  'MAGNAMED-REQUISIÇÃO',
              'SUZANO/Zhongxun Medical',
                        'SUZANO/Resmed',
 'L C DADDE COM AT INST MAT MEDICO EPP',
                  'MAGNAMED/REQUISIÇÃO',
                             'Leistung']
Length: 16, dtype: str

In [42]:
df['TIPO'].unique()

<StringArray>
['UTI', 'TRANSPORTE', 'TRANSPORTE USA', 'Transporte']
Length: 4, dtype: str

In [46]:
df['DESTINATARIO'].unique().size

944

In [47]:
df.to_csv('datasets/distribuicao_respiradores-modificado.csv', index = False, sep = ';')

In [48]:
df.to_excel('datasets/distribuicao_respiradores-modificado.xlsx')

### Exercício 5 - 6

In [54]:
df = pd.read_csv('datasets/CardioGoodFitness.csv',sep=',')

In [55]:
df.shape

(180, 9)

In [56]:
df.head(3)

  Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66

In [57]:
df.tail(2)

,Product,Age,Gender,Education,MaritalStatus,Usage,Fitness,Income,Miles
178,TM798,47,Male,18,Partnered,4,5,104581,120
179,TM798,48,Male,18,Partnered,4,5,95508,180

In [59]:
df.dtypes

Product            str
Age              int64
Gender             str
Education        int64
MaritalStatus      str
Usage            int64
Fitness          int64
Income           int64
Miles            int64
dtype: object

In [60]:
df['Income'] = df['Income'].astype(float)

In [61]:
df.dtypes

Product              str
Age                int64
Gender               str
Education          int64
MaritalStatus        str
Usage              int64
Fitness            int64
Income           float64
Miles              int64
dtype: object

In [63]:
df['Product'].unique()

<StringArray>
['TM195', 'TM498', 'TM798']
Length: 3, dtype: str

In [64]:
df['MaritalStatus'].unique()

<StringArray>
['Single', 'Partnered']
Length: 2, dtype: str

In [67]:
df['Gender'].value_counts()

Gender
Male      104
Female     76
Name: count, dtype: int64

In [68]:
df.to_json('datasets/CardioGoodFitness.json')

### Exercício 7

In [4]:
import requests

In [8]:
df = pd.read_html('https://en.wikipedia.org/wiki/Economy_of_the_United_States')[1]

HTTPError: HTTP Error 403: Forbidden

### Exercício 8

In [10]:
df.to_csv('datasets/indcadores-USA.csv', sep = ';', index = False)

### Exercício 9 - 10

In [11]:
df = pd.read_csv('datasets/FAOSTAT_data_12-5-2020.csv',sep=',')

In [14]:
df.head(5)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,QC,Crops,9,Argentina,5419,Yield,515,Apples,2016,2016,hg/ha,223912,Fc,Calculated data
1,QC,Crops,9,Argentina,5419,Yield,515,Apples,2017,2017,hg/ha,235386,Fc,Calculated data
2,QC,Crops,9,Argentina,5419,Yield,515,Apples,2018,2018,hg/ha,213072,Fc,Calculated data
3,QC,Crops,9,Argentina,5510,Production,515,Apples,2016,2016,tonnes,458908,NaN,Official data
4,QC,Crops,9,Argentina,5510,Production,515,Apples,2017,2017,tonnes,458908,NaN,Official data

In [16]:
df.shape

(66, 14)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       66 non-null     str
 1   Domain            66 non-null     str
 2   Area Code         66 non-null     int64
 3   Area              66 non-null     str
 4   Element Code      66 non-null     int64
 5   Element           66 non-null     str
 6   Item Code         66 non-null     int64
 7   Item              66 non-null     str
 8   Year Code         66 non-null     int64
 9   Year              66 non-null     int64
 10  Unit              66 non-null     str
 11  Value             66 non-null     int64
 12  Flag              43 non-null     str
 13  Flag Description  66 non-null     str
dtypes: int64(6), str(8)
memory usage: 7.3 KB

In [19]:
df.dtypes

Domain Code           str
Domain                str
Area Code           int64
Area                  str
Element Code        int64
Element               str
Item Code           int64
Item                  str
Year Code           int64
Year                int64
Unit                  str
Value               int64
Flag                  str
Flag Description      str
dtype: object

In [23]:
print(df.columns.tolist())

['Domain Code', 'Domain', 'Area Code', 'Area', 'Element Code', 'Element', 'Item Code', 'Item', 'Year Code', 'Year', 'Unit', 'Value', 'Flag', 'Flag Description']

In [24]:
col = ['Domain Code', 'Domain', 'Area Code', 'Element Code', 'Item Code', 'Year Code', 'Flag', 'Flag Description']
df.drop(columns=col, inplace=True, errors='ignore')

In [25]:
df.dtypes

Area         str
Element      str
Item         str
Year       int64
Unit         str
Value      int64
dtype: object

In [26]:
df = df.astype({'Value':float})

In [27]:
df.to_csv('datasets/FAOSTAT-modificado.csv', index = False)